// Generated by commsdsl2comms v3.6.0

#pragma once

#include <QtCore/QVariantMap>

namespace demo1
{

namespace cc_plugin
{

namespace field
{

QVariantMap createProps_propRemLen(const char* name, bool serHidden = false);

} // namespace field

} // namespace cc_plugin

} // namespace demo1


