// Generated by commsdsl2comms v6.3.4

/// @file
/// @brief Contains definition of <b>"Simple Ints"</b> message and its fields.

#pragma once

#include <cstdint>
#include <tuple>
#include "cc_demo1/MsgId.h"
#include "cc_demo1/field/FieldBase.h"
#include "cc_demo1/message/SimpleIntsCommon.h"
#include "cc_demo1/options/DefaultOptions.h"
#include "comms/MessageBase.h"
#include "comms/field/IntValue.h"
#include "comms/options.h"

namespace cc_demo1
{

namespace message
{

/// @brief Fields of @ref SimpleInts.
/// @tparam TOpt Extra options
/// @see @ref SimpleInts
/// @headerfile cc_demo1/message/SimpleInts.h
template <typename TOpt = cc_demo1::options::DefaultOptions>
struct SimpleIntsFields
{
    /// @brief Definition of <b>"F1"</b> field.
    class F1 : public
        comms::field::IntValue<
            cc_demo1::field::FieldBase<>,
            std::int8_t,
            comms::option::def::DefaultNumValue<1>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_demo1::field::FieldBase<>,
                std::int8_t,
                comms::option::def::DefaultNumValue<1>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Single special value name info entry.
        using SpecialNameInfo = cc_demo1::message::SimpleIntsFieldsCommon::F1Common::SpecialNameInfo;

        /// @brief Type returned from @ref specialNamesMap() member function.
        /// @details The @b first value of the pair is pointer to the map array,
        ///     The @b second value of the pair is the size of the array.
        using SpecialNamesMapInfo = cc_demo1::message::SimpleIntsFieldsCommon::F1Common::SpecialNamesMapInfo;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F1Common::hasSpecials();
        }

        /// @brief Special value <b>"S1"</b>.
        /// @see @ref cc_demo1::message::SimpleIntsFieldsCommon::F1Common::valueS1().
        static constexpr ValueType valueS1()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F1Common::valueS1();
        }

        /// @brief Check the value is equal to special @ref valueS1().
        bool isS1() const
        {
            return Base::getValue() == valueS1();
        }

        /// @brief Assign special value @ref valueS1() to the field.
        void setS1()
        {
            Base::setValue(valueS1());
        }

        /// @brief Retrieve map of special value names
        static SpecialNamesMapInfo specialNamesMap()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F1Common::specialNamesMap();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F1Common::name();
        }
    };

    /// @brief Definition of <b>"F2"</b> field.
    class F2 : public
        comms::field::IntValue<
            cc_demo1::field::FieldBase<>,
            std::uint8_t,
            comms::option::def::DefaultNumValue<2>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_demo1::field::FieldBase<>,
                std::uint8_t,
                comms::option::def::DefaultNumValue<2>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F2Common::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F2Common::name();
        }
    };

    /// @brief Definition of <b>"F3"</b> field.
    class F3 : public
        comms::field::IntValue<
            cc_demo1::field::FieldBase<>,
            std::int16_t,
            comms::option::def::DefaultNumValue<3>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_demo1::field::FieldBase<>,
                std::int16_t,
                comms::option::def::DefaultNumValue<3>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F3Common::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F3Common::name();
        }
    };

    /// @brief Definition of <b>"F4"</b> field.
    class F4 : public
        comms::field::IntValue<
            cc_demo1::field::FieldBase<>,
            std::uint16_t,
            comms::option::def::DefaultNumValue<4>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_demo1::field::FieldBase<>,
                std::uint16_t,
                comms::option::def::DefaultNumValue<4>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F4Common::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F4Common::name();
        }
    };

    /// @brief Definition of <b>"F5"</b> field.
    class F5 : public
        comms::field::IntValue<
            cc_demo1::field::FieldBase<>,
            std::int32_t,
            comms::option::def::DefaultNumValue<5>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_demo1::field::FieldBase<>,
                std::int32_t,
                comms::option::def::DefaultNumValue<5>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F5Common::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F5Common::name();
        }
    };

    /// @brief Definition of <b>"F6"</b> field.
    class F6 : public
        comms::field::IntValue<
            cc_demo1::field::FieldBase<>,
            std::uint32_t,
            comms::option::def::DefaultNumValue<6>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_demo1::field::FieldBase<>,
                std::uint32_t,
                comms::option::def::DefaultNumValue<6>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Single special value name info entry.
        using SpecialNameInfo = cc_demo1::message::SimpleIntsFieldsCommon::F6Common::SpecialNameInfo;

        /// @brief Type returned from @ref specialNamesMap() member function.
        /// @details The @b first value of the pair is pointer to the map array,
        ///     The @b second value of the pair is the size of the array.
        using SpecialNamesMapInfo = cc_demo1::message::SimpleIntsFieldsCommon::F6Common::SpecialNamesMapInfo;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F6Common::hasSpecials();
        }

        /// @brief Special value <b>"S1"</b>.
        /// @see @ref cc_demo1::message::SimpleIntsFieldsCommon::F6Common::valueS1().
        static constexpr ValueType valueS1()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F6Common::valueS1();
        }

        /// @brief Check the value is equal to special @ref valueS1().
        bool isS1() const
        {
            return Base::getValue() == valueS1();
        }

        /// @brief Assign special value @ref valueS1() to the field.
        void setS1()
        {
            Base::setValue(valueS1());
        }

        /// @brief Retrieve map of special value names
        static SpecialNamesMapInfo specialNamesMap()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F6Common::specialNamesMap();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F6Common::name();
        }
    };

    /// @brief Definition of <b>"F7"</b> field.
    class F7 : public
        comms::field::IntValue<
            cc_demo1::field::FieldBase<>,
            std::int64_t,
            comms::option::def::DefaultNumValue<7>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_demo1::field::FieldBase<>,
                std::int64_t,
                comms::option::def::DefaultNumValue<7>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F7Common::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F7Common::name();
        }
    };

    /// @brief Definition of <b>"F8"</b> field.
    class F8 : public
        comms::field::IntValue<
            cc_demo1::field::FieldBase<>,
            std::uint64_t,
            comms::option::def::DefaultNumValue<8>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_demo1::field::FieldBase<>,
                std::uint64_t,
                comms::option::def::DefaultNumValue<8>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F8Common::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F8Common::name();
        }
    };

    /// @brief Definition of <b>"F9"</b> field.
    class F9 : public
        comms::field::IntValue<
            cc_demo1::field::FieldBase<>,
            std::int32_t,
            comms::option::def::VarLength<1U, 4U>,
            comms::option::def::DefaultNumValue<9>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_demo1::field::FieldBase<>,
                std::int32_t,
                comms::option::def::VarLength<1U, 4U>,
                comms::option::def::DefaultNumValue<9>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F9Common::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F9Common::name();
        }
    };

    /// @brief Definition of <b>"F10"</b> field.
    /// @details
    ///     Using little endian (LEB-128) to encode this field.
    class F10 : public
        comms::field::IntValue<
            cc_demo1::field::FieldBase<comms::option::def::LittleEndian>,
            std::uint32_t,
            comms::option::def::VarLength<1U, 4U>,
            comms::option::def::DefaultNumValue<10>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_demo1::field::FieldBase<comms::option::def::LittleEndian>,
                std::uint32_t,
                comms::option::def::VarLength<1U, 4U>,
                comms::option::def::DefaultNumValue<10>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F10Common::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_demo1::message::SimpleIntsFieldsCommon::F10Common::name();
        }
    };

    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10
    >;
};

/// @brief Definition of <b>"Simple Ints"</b> message class.
/// @details
///     See @ref SimpleIntsFields for definition of the fields this message contains.
/// @tparam TMsgBase Base (interface) class.
/// @tparam TOpt Extra options
/// @headerfile cc_demo1/message/SimpleInts.h
template <typename TMsgBase, typename TOpt = cc_demo1::options::DefaultOptions>
class SimpleInts : public
    comms::MessageBase<
        TMsgBase,
        typename TOpt::message::SimpleInts,
        comms::option::def::StaticNumIdImpl<cc_demo1::MsgId_SimpleInts>,
        comms::option::def::FieldsImpl<typename SimpleIntsFields<TOpt>::All>,
        comms::option::def::MsgType<SimpleInts<TMsgBase, TOpt> >,
        comms::option::def::HasName
    >
{
    // Redefinition of the base class type
    using Base =
        comms::MessageBase<
            TMsgBase,
            typename TOpt::message::SimpleInts,
            comms::option::def::StaticNumIdImpl<cc_demo1::MsgId_SimpleInts>,
            comms::option::def::FieldsImpl<typename SimpleIntsFields<TOpt>::All>,
            comms::option::def::MsgType<SimpleInts<TMsgBase, TOpt> >,
            comms::option::def::HasName
        >;

public:
    /// @brief Provide names and allow access to internal fields.
    /// @details See definition of @b COMMS_MSG_FIELDS_NAMES macro
    ///     related to @b comms::MessageBase class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and functions are:
    ///     @li @b FieldIdx_f1 index, @b Field_f1 type and @b field_f1() access fuction
    ///         for @ref SimpleIntsFields::F1 field.
    ///     @li @b FieldIdx_f2 index, @b Field_f2 type and @b field_f2() access fuction
    ///         for @ref SimpleIntsFields::F2 field.
    ///     @li @b FieldIdx_f3 index, @b Field_f3 type and @b field_f3() access fuction
    ///         for @ref SimpleIntsFields::F3 field.
    ///     @li @b FieldIdx_f4 index, @b Field_f4 type and @b field_f4() access fuction
    ///         for @ref SimpleIntsFields::F4 field.
    ///     @li @b FieldIdx_f5 index, @b Field_f5 type and @b field_f5() access fuction
    ///         for @ref SimpleIntsFields::F5 field.
    ///     @li @b FieldIdx_f6 index, @b Field_f6 type and @b field_f6() access fuction
    ///         for @ref SimpleIntsFields::F6 field.
    ///     @li @b FieldIdx_f7 index, @b Field_f7 type and @b field_f7() access fuction
    ///         for @ref SimpleIntsFields::F7 field.
    ///     @li @b FieldIdx_f8 index, @b Field_f8 type and @b field_f8() access fuction
    ///         for @ref SimpleIntsFields::F8 field.
    ///     @li @b FieldIdx_f9 index, @b Field_f9 type and @b field_f9() access fuction
    ///         for @ref SimpleIntsFields::F9 field.
    ///     @li @b FieldIdx_f10 index, @b Field_f10 type and @b field_f10() access fuction
    ///         for @ref SimpleIntsFields::F10 field.
    COMMS_MSG_FIELDS_NAMES(
        f1,
        f2,
        f3,
        f4,
        f5,
        f6,
        f7,
        f8,
        f9,
        f10
    );

    // Compile time check for serialisation length.
    static const std::size_t MsgMinLen = Base::doMinLength();
    static const std::size_t MsgMaxLen = Base::doMaxLength();
    static_assert(MsgMinLen == 32U, "Unexpected min serialisation length");
    static_assert(MsgMaxLen == 38U, "Unexpected max serialisation length");

    /// @brief Name of the message.
    static const char* doName()
    {
        return cc_demo1::message::SimpleIntsCommon::name();
    }
};

} // namespace message

} // namespace cc_demo1
