// Generated by commsdsl2comms v5.2.0

/// @file
/// @brief Contains definition of the AllMessages messages bundle.

#pragma once

#include <tuple>
#include "cc_demo1/message/Ack.h"
#include "cc_demo1/message/Bitfields.h"
#include "cc_demo1/message/Datas.h"
#include "cc_demo1/message/Enums.h"
#include "cc_demo1/message/Floats.h"
#include "cc_demo1/message/Lists.h"
#include "cc_demo1/message/Optionals.h"
#include "cc_demo1/message/ScaledInts.h"
#include "cc_demo1/message/Sets.h"
#include "cc_demo1/message/SimpleInts.h"
#include "cc_demo1/message/Strings.h"
#include "cc_demo1/message/Variants.h"
#include "cc_demo1/options/DefaultOptions.h"

namespace cc_demo1
{

namespace input
{

/// @brief Messages of the protocol in ascending order.
/// @tparam TBase Base class of all the messages.
/// @tparam TOpt Protocol definition options.
template <typename TBase, typename TOpt = cc_demo1::options::DefaultOptions>
using AllMessages =
    std::tuple<
        cc_demo1::message::Ack<TBase, TOpt>,
        cc_demo1::message::SimpleInts<TBase, TOpt>,
        cc_demo1::message::ScaledInts<TBase, TOpt>,
        cc_demo1::message::Floats<TBase, TOpt>,
        cc_demo1::message::Enums<TBase, TOpt>,
        cc_demo1::message::Sets<TBase, TOpt>,
        cc_demo1::message::Bitfields<TBase, TOpt>,
        cc_demo1::message::Strings<TBase, TOpt>,
        cc_demo1::message::Datas<TBase, TOpt>,
        cc_demo1::message::Lists<TBase, TOpt>,
        cc_demo1::message::Optionals<TBase, TOpt>,
        cc_demo1::message::Variants<TBase, TOpt>
    >;

} // namespace input

} // namespace cc_demo1
